### ISSUE TITLE
'Then I should see' question

### ISSUE THREAD

**Issue by p2635** [arnaud-dezandee/cucumber-mink#344]
Sorry if this is the wrong place to post questions.

I can make 'Then I should see' work for normal strings on the page but if I have something like this, it fails:
'This is text with link A, link B and link C' (where link A, link B and link C are actual hyperlinks)

How would I make it pass? Is there an alternative step I should use? (I'm using Behat)

**Comment by brockfanning** [comment]
@p2635 You mention Behat, so it's possible you posted in the wrong place. This project is a Javascript library, and not connected to Behat (though it is _inspired_ by Behat/Mink I believe).

As for how "I should see" works in this library, see [here](http://cucumber-mink.js.org/steps/#html-contains). It looks for the string in the HTML. So in your case I believe you would need something like: `This is text with <a href="...">link A</a>, <a href="...">link B</a>, etc...`

**Comment by p2635** [comment]
Thanks @brockfanning  this is so old that I forgot about it and no longer relevant. Thanks for reaching out though and  sorry for posting in the wrong place!
